# Generated by Django 3.2.16 on 2023-01-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reviewimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
