# Generated by Django 3.2.16 on 2023-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_watchlist_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
