# Generated by Django 3.2.16 on 2023-01-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230105_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='reviewinfo',
        ),
    ]
