# Generated by Django 3.2.16 on 2023-01-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_image', to='reviews.reviewinfo'),
        ),
    ]
