# Generated by Django 3.2.16 on 2023-01-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230105_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewinfo'),
        ),
    ]
