# Generated by Django 3.2.16 on 2023-01-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_reviewimage_movie2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
