# Generated by Django 3.2.16 on 2023-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_delete_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinfo',
            name='has_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
