# Generated by Django 3.2.16 on 2023-01-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_reviewinfo_has_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewinfo',
            name='has_reviewed',
        ),
    ]
