# Generated by Django 3.2.16 on 2023-01-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_genres',
            field=models.ManyToManyField(to='accounts.Genre'),
        ),
    ]
